### ISSUE TITLE
MySQL Integrity Error on scanner.py

### ISSUE THREAD

**Issue by justinledford** [smuseniordesignmod0/InSecurity-API#1]
With fresh install, running `python3 scanner.py 1` fails with an Integrity Error exception:

```
Traceback (most recent call last):
  File "scanner.py", line 282, in <module>
    main()
  File "scanner.py", line 260, in main
    log_activity('Preparing for scan:')
  File "scanner.py", line 228, in log_activity
    c.execute("INSERT INTO ActivityLog (id, message) VALUES (%s, %s)", (scan_id, log_string))
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 217, in execute
    res = self._query(query)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 378, in _query
    rowcount = self._do_query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/cursors.py", line 341, in _do_query
    db.query(q)
  File "/usr/lib/python3/dist-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`InSecurity`.`ActivityLog`, CONSTRAINT `ActivityLog_ibfk_1` FOREIGN KEY (`id`) REFERENCES `Scan` (`id`))')

```

**Comment by LittleBoxOfSunshine** [comment]
Running the scan requires that there is a corresponding entry in the "Scan" table. Try using the endpoint /Scanner/Scan to create a scan (it will also run the python script the same way you have here), OR (and this is the easier way IMO) use the command line or phpmyadmin (installed via vagrant by default) to insert a new row into the "Scan" table. The error you're seeing should go away.
